// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using helpdesk_ticketing_system_api.data;

#nullable disable

namespace helpdesk_ticketing_system_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514231142_fixEverything")]
    partial class fixEverything
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("helpdesk_ticketing_system_api.data.Employee", b =>
                {
                    b.Property<int>("employeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employeeID"));

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("employeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("helpdesk_ticketing_system_api.data.HelpdeskTicket", b =>
                {
                    b.Property<int>("ticketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ticketID"));

                    b.Property<int>("employeeID")
                        .HasColumnType("integer");

                    b.Property<int>("technicianID")
                        .HasColumnType("integer");

                    b.Property<string>("ticketDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ticketStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ticketTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ticketID");

                    b.HasIndex("employeeID");

                    b.HasIndex("technicianID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("helpdesk_ticketing_system_api.data.Technician", b =>
                {
                    b.Property<int>("technicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("technicianID"));

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("technicianID");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("helpdesk_ticketing_system_api.data.HelpdeskTicket", b =>
                {
                    b.HasOne("helpdesk_ticketing_system_api.data.Employee", "employee")
                        .WithMany("tickets")
                        .HasForeignKey("employeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("helpdesk_ticketing_system_api.data.Technician", "technician")
                        .WithMany("tickets")
                        .HasForeignKey("technicianID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("technician");
                });

            modelBuilder.Entity("helpdesk_ticketing_system_api.data.Employee", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("helpdesk_ticketing_system_api.data.Technician", b =>
                {
                    b.Navigation("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
